/*  Client will running until the LEAVE command is recieve or "Ctrl+c"  */

#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <signal.h>
#include <unistd.h>
#include <fcntl.h>	/* Defines O_* constants  */
#include <sys/stat.h>	/* Defines mode constants */
#include <sys/mman.h>
#include <sys/types.h>
#include <pthread.h>

#include "mailbox_toolkit.h"

static volatile int shutdown = 1;
int id;
char *name;

/* Initialize the mail */
void mail_init(mail_t **mail)
{
    *mail = malloc(sizeof(mail_t));
    (*mail)->from = id;
    strcpy((*mail)->sstr, name);
}

void print_help()
{
    printf( "\nRoom Option:\n"
	    "--LIST    : List the room members\n"
	    "--LEAVE   : Leave the room\n"
	    "--WHISPER : Priave message\n"
	    "--HELP    : Get more information\n\n" );
}

void recv(void *args)
{
    mail_t *mail;
    mail = malloc(sizeof(mail_t));
    Mail_box_t *box = (Mail_box_t*)args;
    while (shutdown) {
	while (box->in == box->out && shutdown);

	/* Are we leaveing? */
	if (!shutdown) break;

	mailbox_recv(box, mail);
	switch(mail->type){
	    case SERVER:
		printf("%s\n",mail->lstr);	//Mail from server
		break;

	    case WHISPER:
		printf("\nPriave message from %s: %s\n\n",mail->sstr, mail->lstr);
		break;

	    default: 
		printf("\nFrom %s: %s\n\n", mail->sstr, mail->lstr);
		break;
	}
    }
}

void send(void *args)
{
    mail_t *mail;
    Mail_box_t *server = (Mail_box_t*)args;
    mail_init(&mail);
    while (shutdown) {
	int i = 0;
	/* Get line and replace the newline with '\0 */
	fgets(mail->lstr, SIZE_OF_LONG_STRING, stdin); 
	while (mail->lstr[i] != '\0') 
	    i++;
	mail->lstr[i-1] = '\0';

	/* Checking type */
	if (strcmp(mail->lstr, "--LEAVE") == 0) {
	    mail->type = LEAVE;

	    /* Wait if server mailbox is fulled */
	    while (mailbox_check_full(server)); 
	    mailbox_send(server, mail);
	    shutdown = 0;   // shut down the process
	}

	else if (strcmp(mail->lstr, "--LIST") == 0) {
	    mail->type = LIST;

	    /* Wait if server mailbox is fulled */
	    while (mailbox_check_full(server)); 
	    mailbox_send(server, mail);
	}

	else if (strcmp(mail->lstr, "--HELP") == 0) {
	    print_help();
	}

	else if (strcmp(mail->lstr, "--WHISPER") == 0) {
	    printf("Choose a person for private message\n");
	    /* List the room members for the user first */
	    mail->type = LIST;

	    /* Wait if server mailbox is fulled */
	    while (mailbox_check_full(server)); 
	    mailbox_send(server,mail);

	    /* For whisper :	     *
	     *	mail.from = sender   *
	     *	mail.type = WHISPER  *
	     *	mail.sstr = reciever *
	     *	mail.lstr = message  */
	    i = 0;
	    mail->type = WHISPER;

	    /* Get the person for whisper */
	    char reciever[SIZE_OF_SHORT_STRING];
	    scanf("%s",reciever);
	    memcpy(mail->sstr, reciever, sizeof(reciever));
	    getchar();	//get the remain newline,which generated by scanf

	    /* Get the message */
	    printf("Enter your message: ");
	    fgets(mail->lstr, SIZE_OF_LONG_STRING, stdin); 
	    while (mail->lstr[i] != '\0') 
		i++;
	    mail->lstr[i-1] = '\0';
	   
	    /* Wait if server mailbox is fulled */
	    while (mailbox_check_full(server)); 
	    mailbox_send(server,mail);        	    
	}

	else {
	    mail->type = BROADCAST;
	    /* Wait if server mailbox is fulled */
	    while (mailbox_check_full(server)); 
	    mailbox_send(server, mail);
	}
    }
}

/* For "Ctrl+C" interrupt */
void handler()
{
    while(1){
	if (!mailbox_unlink(id))
	    break;
    }
    shutdown = 0;
}

int main(int argc, char *argv[])
{
    if(argc != 3){
	printf("Usage: ./client \"id\" \"name\" \n");
	return -1;
    }
    
    printf( "Welcome to the chat room!\n" 
	    "For more imformation, please enter \"--HELP\" \n");
    
    /* For "Ctrl+C" interrupt */
    signal(SIGINT,handler);

    id = atoi(argv[1]);
    name = argv[2];

    /* Initialize mail box */
    Mail_box_t *box, *server;
    server = (Mail_box_t*)mailbox_open(0);
    box = (Mail_box_t*)mailbox_open(id);
    box->in = 0;
    box->out = 0;

    /* Initialize mail type and name */
    mail_t *mail;
    mail_init(&mail);
    mail->type = JOIN;

    /* Wait if server mailbox is fulled */
    while (mailbox_check_full(server)); 
    mailbox_send(server,mail);

    /* @Thread_s : For send *
     * @Thread_r : For recv *
     * Non-blocking I/O	    */
    pthread_t Thread_s, Thread_r;
    pthread_create(&Thread_r, NULL, (void*)recv, (void*)box);
    pthread_create(&Thread_s, NULL, (void*)send, (void*)server);

    pthread_join(Thread_r, NULL);
    pthread_join(Thread_s, NULL);

    printf("\nBYEBYE!\n");
    return 0;
}
